FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_BASE_URL
ARG PORT=4173
ENV VITE_BASE_URL=$VITE_BASE_URL
ENV PORT=$PORT

RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY --from=builder /app/dist ./dist

EXPOSE 4173

CMD ["npm", "run", "preview"]