version: "3.9"

library-services:
  backend:
    build:
      network: host
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: library_backend_dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env.dev
    depends_on:
      - library-mongodb
    restart: unless-stopped

  library-frontend:
    build:
      network: host
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: library_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env.dev
    depends_on:
      - library-backend
    restart: unless-stopped

  library-mongodb:
    image: mongo:7
    container_name: library_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.dev
    restart: unless-stopped

volumes:
  mongo_data:
